targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      hive_generator:hive_generator:
        generate_for:
          include:
            - lib/**/*.dart