name: real_estate_fe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  sentry_flutter: ^8.14.0
  stacked: ^3.4.0
  stacked_hooks: ^0.2.4
  stacked_services: ^1.1.0
  flutter_gen: ^5.10.0
  localize_and_translate: 4.1.1
  currency_formatter: ^2.2.2
  supercharged: ^2.1.1
  rx_shared_preferences: ^4.0.0
  velocity_x: ^4.3.0
  flutter_image_compress: ^2.4.0
  jiffy: ^6.3.2
  dartx: ^1.2.0
  dio_http_cache_lts: ^0.4.2
  translator: ^0.1.7
  basic_utils: ^5.5.4
  custom_clippers: ^2.0.0
  cached_network_image: ^3.3.1
  pinch_zoom: ^2.0.0
  keyboard_dismisser: ^3.0.0
  measure_size: ^4.0.0
  google_fonts: ^4.0.4
  adaptive_theme: ^3.7.0
  pull_to_refresh_flutter3: ^2.0.2
  flutter_typeahead: ^5.2.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  flutter_signin_button: ^2.0.0
  firebase_core: ^3.12.1

  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  device_info_plus: ^11.3.0
  awesome_dialog: ^3.2.1
  photo_view: ^0.15.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_html: ^3.0.0
  image_picker: ^1.1.2
  geolocator: ^13.0.4
  flutter_map: ^4.0.0
  flutter_form_builder: ^9.7.0
  latlong2: ^0.8.2
  flutter_quill: ^11.2.0
  notus: ^1.0.0-rc.2
  flutter_quill_delta_from_html: ^1.5.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  build_runner: ^2.4.5
  freezed: ^2.0.0
  json_serializable: ^6.9.0

dependency_overrides:
  rxdart: ^0.28.0
  intl: ^0.20.1
flutter:
  assets:
    - assets/.env
    - assets/lang/
    - assets/images/
  uses-material-design: true
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  # android: true
  # ios: false
  # web: false